### PR TITLE
feat: Update tokenizer to parse "abc"abd kinds

### PR DESCRIPTION
**Pull request by san-ghun**
- Our 미쉘 can parse `"abc"abc` kind of unspaced cmd as token.
- Our 미쉘 can process execution of absolute path command, like `/usr/bin/ls -al`.

### CODE REVIEW

**Comment by san-ghun** [comment]
Not a perfect but,
```bash
미쉘> echo "abc"adb
abc -----> abcadc
```
is now done.

**Comment by miooo0o** [comment]
```
미쉘(debug)> echo "           here is"abc
[echo] [] [here] [isabc] 

call sent_print(): printing sentence(s), head to tail.
p_unit: [echo  here isabc]
input: 0, (null)
output: 1, (null)
[0: echo] [1: ] [2: here] [3: isabc] 

------ result ------
here isabc미쉘(debug)> exit
[exit] 

call sent_print(): printing sentence(s), head to tail.
p_unit: [exit]
input: 0, (null)
output: 1, (null)
[0: exit] 

```

**Comment by miooo0o** [comment]
```
미쉘(debug)> echo "           here is"abc
[echo] [] [here] [isabc] 

call sent_print(): printing sentence(s), head to tail.
p_unit: [echo  here isabc]
input: 0, (null)
output: 1, (null)
[0: echo] [1: ] [2: here] [3: isabc] 

------ result ------
here isabc미쉘(debug)> exit
[exit] 

call sent_print(): printing sentence(s), head to tail.
p_unit: [exit]
input: 0, (null)
output: 1, (null)
[0: exit] 
```

이렇게 parse되고 있어서 수정이 필요해보입니다... 점점 미니쉘 싫어지는 중 :(

**Comment by san-ghun** [comment]
```bash
미쉘(debug)> echo "           here is"abc
[echo] [           here isabc]

call sent_print(): printing sentence(s), head to tail.
p_unit: [echo            here isabc]
input: 0, (null)
output: 1, (null)
[0: echo] [1:            here isabc]

------ result ------
           here isabc
```
now 👍

**Review by miooo0o — APPROVED** [review]
time to eval now

**Pull request merged**
